---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-apps 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: applications-project
  source:
    repoURL: https://github.com/r44rs/eks-gitops-crossplane-argocd.git
    targetRevision: HEAD
    path: workload-apps
    helm:
      values: |
        spec:
          destination:
            server: https://025669CCBFE6C7FD5713BFE28C5E5A74.gr7.us-east-1.eks.amazonaws.com       
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true    